### ISSUE TITLE
Styleguide server started at http://:::3000

### ISSUE THREAD

**Issue by paulrobertlloyd** [webpro/component-styleguide#9]
Tiny bug, but seen on two separate instances (one Mac OS X, one on Windows). When the server starts, it reports as running on `http://:::3000`. Should this not report `http://localhost:3000` instead?

**Comment by webpro** [comment]
Agreed it doesn't look great, but this is how Node `http` module works (https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback), I don't think we should force anything here. I'd be happy to look how others are doing this, but since I think it's pretty minor I'm going to close this for now.

**Comment by boutell** [comment]
Just came across this as I'm addressing it in my own application. I know it's a dead ticket, but FWIW, in 2020 Chrome still won't open that, so it's probably worth recognizing :: and converting it to localhost.
